spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true (systemOut 찍음)
        format_sql: true
    repositories:
      bootstrap-mode: default

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace